# Generated by Django 6.0.7 on 2026-07-22

from django.db import migrations, models


def convert_in_progress_to_pending(apps, schema_editor):
    Todo = apps.get_model('todos', 'Todo')
    Todo.objects.filter(status='in_progress').update(status='pending')


class Migration(migrations.Migration):
    dependencies = [
        ('todos', '0002_todo_timestamps'),
    ]

    operations = [
        migrations.RunPython(convert_in_progress_to_pending, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('done', 'Done')],
                default='pending',
                max_length=20,
            ),
        ),
    ]
